/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package clases;

import javax.swing.JOptionPane;
/**
 *
 * @author JESUS EMMANUEL
 */
public class Ventana1_copy extends javax.swing.JInternalFrame {
    public int contador = 0,contador2 = 0 ;
    private Operaciones operacion;
    private Validaciones validacion;
    /**
     * Creates new form Ventana
     */
    public Ventana1_copy() {
        initComponents();
        this.validacion = new Validaciones();
        this.operacion = new Operaciones();
        //para inicialisar los valores de las opciones
        this.optSuma.setActionCommand("suma");
        this.optResta.setActionCommand("resta");
        this.optMultiplicacion.setActionCommand("multiplicacion");
        this.optDivision.setActionCommand("division");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        btnCalcular = new javax.swing.JButton();
        jPanel10 = new javax.swing.JPanel();
        btnCerrar = new javax.swing.JButton();
        jPanel9 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        btnSuma = new javax.swing.JButton();
        btnResta = new javax.swing.JButton();
        btnMultiplicacion = new javax.swing.JButton();
        btnDivision = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        optSuma = new javax.swing.JRadioButton();
        optResta = new javax.swing.JRadioButton();
        optMultiplicacion = new javax.swing.JRadioButton();
        optDivision = new javax.swing.JRadioButton();
        jPanel2 = new javax.swing.JPanel();
        jPanel11 = new javax.swing.JPanel();
        txtNumeroUno = new javax.swing.JTextField();
        txtNumeroDos = new javax.swing.JTextField();
        jPanel12 = new javax.swing.JPanel();
        lblResultado = new javax.swing.JLabel();

        setClosable(true);
        setTitle("Operaciones");

        jPanel1.setLayout(new java.awt.BorderLayout());

        jPanel3.setPreferredSize(new java.awt.Dimension(394, 50));
        jPanel3.setLayout(new java.awt.GridLayout(1, 1));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Operaciones Aritmeticas");
        jPanel3.add(jLabel1);

        jPanel1.add(jPanel3, java.awt.BorderLayout.PAGE_START);

        jPanel4.setPreferredSize(new java.awt.Dimension(394, 80));
        jPanel4.setLayout(new java.awt.GridLayout(1, 4));

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 124, Short.MAX_VALUE)
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 80, Short.MAX_VALUE)
        );

        jPanel4.add(jPanel8);

        jPanel7.setLayout(new java.awt.GridLayout(1, 1));

        btnCalcular.setText("Calcular");
        btnCalcular.setEnabled(false);
        btnCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalcularActionPerformed(evt);
            }
        });
        jPanel7.add(btnCalcular);

        jPanel4.add(jPanel7);

        jPanel10.setLayout(new java.awt.GridLayout(1, 1));

        btnCerrar.setText("Cerrar");
        btnCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarActionPerformed(evt);
            }
        });
        jPanel10.add(btnCerrar);

        jPanel4.add(jPanel10);

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 124, Short.MAX_VALUE)
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 80, Short.MAX_VALUE)
        );

        jPanel4.add(jPanel9);

        jPanel1.add(jPanel4, java.awt.BorderLayout.PAGE_END);

        jPanel5.setLayout(new java.awt.GridLayout(4, 1, 0, 4));

        btnSuma.setText("Suma");
        btnSuma.setEnabled(false);
        btnSuma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSumaActionPerformed(evt);
            }
        });
        jPanel5.add(btnSuma);

        btnResta.setText("Resta");
        btnResta.setEnabled(false);
        btnResta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRestaActionPerformed(evt);
            }
        });
        jPanel5.add(btnResta);

        btnMultiplicacion.setText("Multiplicación");
        btnMultiplicacion.setEnabled(false);
        btnMultiplicacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMultiplicacionActionPerformed(evt);
            }
        });
        jPanel5.add(btnMultiplicacion);

        btnDivision.setText("Division");
        btnDivision.setEnabled(false);
        btnDivision.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDivisionActionPerformed(evt);
            }
        });
        jPanel5.add(btnDivision);

        jPanel1.add(jPanel5, java.awt.BorderLayout.LINE_END);

        jPanel6.setLayout(new java.awt.GridLayout(4, 1, 0, 4));

        buttonGroup1.add(optSuma);
        optSuma.setSelected(true);
        optSuma.setText("Suma");
        optSuma.setEnabled(false);
        jPanel6.add(optSuma);

        buttonGroup1.add(optResta);
        optResta.setText("Resta");
        optResta.setEnabled(false);
        jPanel6.add(optResta);

        buttonGroup1.add(optMultiplicacion);
        optMultiplicacion.setText("Multiplicación");
        optMultiplicacion.setEnabled(false);
        jPanel6.add(optMultiplicacion);

        buttonGroup1.add(optDivision);
        optDivision.setText("Division");
        optDivision.setEnabled(false);
        jPanel6.add(optDivision);

        jPanel1.add(jPanel6, java.awt.BorderLayout.LINE_START);

        jPanel2.setLayout(new java.awt.GridLayout(4, 2));

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 292, Short.MAX_VALUE)
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 58, Short.MAX_VALUE)
        );

        jPanel2.add(jPanel11);

        txtNumeroUno.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNumeroUnoKeyTyped(evt);
            }
        });
        jPanel2.add(txtNumeroUno);

        txtNumeroDos.setMargin(new java.awt.Insets(2, 4, 2, 6));
        txtNumeroDos.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNumeroDosKeyTyped(evt);
            }
        });
        jPanel2.add(txtNumeroDos);

        jPanel12.setLayout(new java.awt.GridLayout(1, 1));

        lblResultado.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblResultado.setText("0.0");
        jPanel12.add(lblResultado);

        jPanel2.add(jPanel12);

        jPanel1.add(jPanel2, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNumeroUnoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNumeroUnoKeyTyped
         //casting implicito de char a ascii, gracias a que un caracter cabe en los 8bits de un entero
        int key = evt.getKeyChar();
        if(key == 8 && contador > 0){
           contador--;
        }
        if((key >= 48 && key <= 57) || key == 46){
            contador++;
        }else{
            evt.consume();
        }
        if(contador > 0 && contador2 > 0){
            this.btnSuma.setEnabled(true);
            this.btnResta.setEnabled(true);
            this.btnMultiplicacion.setEnabled(true);
            this.btnDivision.setEnabled(true);
            this.btnCalcular.setEnabled(true);
            //.....
        }else{
            /*Event.consume() eso quiere decir que el evento se consumirá
            e impide en este caso, el ingreso de mas caracteres.*/
            //evt.consume();
            this.btnCalcular.setEnabled(false);
            this.btnDivision.setEnabled(false);
            this.btnMultiplicacion.setEnabled(false);
            this.btnResta.setEnabled(false);
            this.btnSuma.setEnabled(false);
        }
    }//GEN-LAST:event_txtNumeroUnoKeyTyped

    private void btnCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarActionPerformed
        this.hide();
    }//GEN-LAST:event_btnCerrarActionPerformed

    private void txtNumeroDosKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNumeroDosKeyTyped
        int key = evt.getKeyChar();
        if(key == 8 && contador2 > 0){
           contador2--;
        }
        if((key >= 48 && key <= 57) || key == 46){
            contador2++;
        }else{
            //aborta el evento
            evt.consume();
        }
        if(contador > 0 && contador2 > 0){
            this.btnSuma.setEnabled(true);
            this.btnResta.setEnabled(true);
            this.btnMultiplicacion.setEnabled(true);
            this.btnDivision.setEnabled(true);
            this.btnCalcular.setEnabled(true);
            this.optSuma.setEnabled(true);
            this.optResta.setEnabled(true);
            this.optMultiplicacion.setEnabled(true);
            this.optDivision.setEnabled(true);
            //.....
        }else{
            /*Event.consume() eso quiere decir que el evento se consumirá
            e impide en este caso, el ingreso de mas caracteres.*/
            //evt.consume();
            this.btnCalcular.setEnabled(false);
            this.btnDivision.setEnabled(false);
            this.btnMultiplicacion.setEnabled(false);
            this.btnResta.setEnabled(false);
            this.btnSuma.setEnabled(false);
            this.optSuma.setEnabled(false);
            this.optResta.setEnabled(false);
            this.optMultiplicacion.setEnabled(false);
            this.optDivision.setEnabled(false);
        }
    }//GEN-LAST:event_txtNumeroDosKeyTyped

    private void btnSumaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSumaActionPerformed
        String numeroUno,numeroDos;
        numeroUno = this.txtNumeroUno.getText();
        numeroDos = this.txtNumeroDos.getText();
        float numeroUnoFloat, numeroDosFloat;
        
        if(this.validacion.validarNumeros(numeroUno).equals("decimal")){
            //JOptionPane.showMessageDialog(null,"el numero es un entero");
            //Preguntas de decimal - entero y decimal - decimal Asi como entero - decimal y entero - entero
            if(this.validacion.validarNumeros(numeroDos).equals("decimal")){
                numeroUnoFloat = Float.parseFloat(numeroUno);
                numeroDosFloat = Float.parseFloat(numeroDos);    
                this.lblResultado.setText(Float.toString(this.operacion.suma(numeroUnoFloat, numeroDosFloat)));
            }else if(this.validacion.validarNumeros(numeroDos).equals("entero")){
                numeroUnoFloat = Float.parseFloat(numeroUno);
                numeroDosFloat = Float.parseFloat(numeroDos);
                this.lblResultado.setText(Float.toString(this.operacion.suma(numeroUnoFloat, numeroDosFloat)));
            }
            
        }else if(this.validacion.validarNumeros(numeroUno).equals("entero")){
            
            if(this.validacion.validarNumeros(numeroDos).equals("entero")){
                int numeroUnoInt = Integer.parseInt(numeroUno);
                int numeroDosInt = Integer.parseInt(numeroDos);
                this.lblResultado.setText(Integer.toString(this.operacion.suma(numeroUnoInt, numeroDosInt)));
                
            }else if(this.validacion.validarNumeros(numeroDos).equals("decimal")){
               numeroUnoFloat = Float.parseFloat(numeroUno);
               numeroDosFloat = Float.parseFloat(numeroDos);
               this.lblResultado.setText(Float.toString(this.operacion.suma(numeroUnoFloat, numeroDosFloat)));
            }
            
        }
    }//GEN-LAST:event_btnSumaActionPerformed

    private void btnRestaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRestaActionPerformed
        String numeroUno,numeroDos;
        numeroUno = this.txtNumeroUno.getText();
        numeroDos = this.txtNumeroDos.getText();
        float numeroUnoFloat, numeroDosFloat;
        
        if(this.validacion.validarNumeros(numeroUno).equals("decimal")){
            numeroUnoFloat = Float.parseFloat(numeroUno);
            if(this.validacion.validarNumeros(numeroDos).equals("decimal")){
                numeroDosFloat = Float.parseFloat(numeroDos);    
                this.lblResultado.setText(Float.toString(this.operacion.resta(numeroUnoFloat, numeroDosFloat)));
            }else if(this.validacion.validarNumeros(numeroDos).equals("entero")){
                numeroDosFloat = Float.parseFloat(numeroDos);
                this.lblResultado.setText(Float.toString(this.operacion.resta(numeroUnoFloat, numeroDosFloat)));
            }
            
        }else if(this.validacion.validarNumeros(numeroUno).equals("entero")){
            
            if(this.validacion.validarNumeros(numeroDos).equals("entero")){
                int numeroUnoInt = Integer.parseInt(numeroUno);
                int numeroDosInt = Integer.parseInt(numeroDos);
                this.lblResultado.setText(Integer.toString(this.operacion.resta(numeroUnoInt, numeroDosInt)));
                
            }else if(this.validacion.validarNumeros(numeroDos).equals("decimal")){
               numeroUnoFloat = Float.parseFloat(numeroUno);
               numeroDosFloat = Float.parseFloat(numeroDos);
               this.lblResultado.setText(Float.toString(this.operacion.resta(numeroUnoFloat, numeroDosFloat)));
            }
        }
    }//GEN-LAST:event_btnRestaActionPerformed

    private void btnMultiplicacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMultiplicacionActionPerformed
        String numeroUno,numeroDos;
        numeroUno = this.txtNumeroUno.getText();
        numeroDos = this.txtNumeroDos.getText();
        float numeroUnoFloat, numeroDosFloat;
        
        if(this.validacion.validarNumeros(numeroUno).equals("decimal")){
            numeroUnoFloat = Float.parseFloat(numeroUno);
            if(this.validacion.validarNumeros(numeroDos).equals("decimal")){
                numeroDosFloat = Float.parseFloat(numeroDos);    
                this.lblResultado.setText(Float.toString(this.operacion.multiplicacion(numeroUnoFloat, numeroDosFloat)));
            }else if(this.validacion.validarNumeros(numeroDos).equals("entero")){
                numeroDosFloat = Float.parseFloat(numeroDos);
                this.lblResultado.setText(Float.toString(this.operacion.multiplicacion(numeroUnoFloat, numeroDosFloat)));
            }
            
        }else if(this.validacion.validarNumeros(numeroUno).equals("entero")){
            
            if(this.validacion.validarNumeros(numeroDos).equals("entero")){
                int numeroUnoInt = Integer.parseInt(numeroUno);
                int numeroDosInt = Integer.parseInt(numeroDos);
                this.lblResultado.setText(Integer.toString(this.operacion.multiplicacion(numeroUnoInt, numeroDosInt)));
                
            }else if(this.validacion.validarNumeros(numeroDos).equals("decimal")){
               numeroUnoFloat = Float.parseFloat(numeroUno);
               numeroDosFloat = Float.parseFloat(numeroDos);
               this.lblResultado.setText(Float.toString(this.operacion.multiplicacion(numeroUnoFloat, numeroDosFloat)));
            }
        }
    }//GEN-LAST:event_btnMultiplicacionActionPerformed

    private void btnDivisionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDivisionActionPerformed
        String numeroUno,numeroDos;
        numeroUno = this.txtNumeroUno.getText();
        numeroDos = this.txtNumeroDos.getText();
        float numeroUnoFloat, numeroDosFloat;
        
        if(this.validacion.validarNumeros(numeroUno).equals("decimal")){
            numeroUnoFloat = Float.parseFloat(numeroUno);
            if(this.validacion.validarNumeros(numeroDos).equals("decimal")){
                numeroDosFloat = Float.parseFloat(numeroDos);    
                this.lblResultado.setText(Float.toString(this.operacion.division(numeroUnoFloat, numeroDosFloat)));
            }else if(this.validacion.validarNumeros(numeroDos).equals("entero")){
                numeroDosFloat = Float.parseFloat(numeroDos);
                this.lblResultado.setText(Float.toString(this.operacion.division(numeroUnoFloat, numeroDosFloat)));
            }
            
        }else if(this.validacion.validarNumeros(numeroUno).equals("entero")){
            
            if(this.validacion.validarNumeros(numeroDos).equals("entero")){
                int numeroUnoInt = Integer.parseInt(numeroUno);
                int numeroDosInt = Integer.parseInt(numeroDos);
                this.lblResultado.setText(Float.toString(this.operacion.division(numeroUnoInt, numeroDosInt)));
                
            }else if(this.validacion.validarNumeros(numeroDos).equals("decimal")){
               numeroUnoFloat = Float.parseFloat(numeroUno);
               numeroDosFloat = Float.parseFloat(numeroDos);
               this.lblResultado.setText(Float.toString(this.operacion.division(numeroUnoFloat, numeroDosFloat)));
            }
        }
    }//GEN-LAST:event_btnDivisionActionPerformed

    private void btnCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalcularActionPerformed
        //Para extraer el valor de la opcion seleccionada
        String _operacion = this.buttonGroup1.getSelection().getActionCommand();
        String numeroUno = this.txtNumeroUno.getText();
        String numeroDos = this.txtNumeroDos.getText();
        
        if(this.optSuma.isSelected()){
            int a = Integer.parseInt(numeroUno);
            int b = Integer.parseInt(numeroDos);
            int resultado = a+b;
            this.lblResultado.setText(Integer.toString(resultado));
        }
        if(this.optResta.isSelected()){
            int a = Integer.parseInt(numeroUno);
            int b = Integer.parseInt(numeroDos);
            int resultado = a-b;
            this.lblResultado.setText(Integer.toString(resultado));
        }
        if(this.optMultiplicacion.isSelected()){
            int a = Integer.parseInt(numeroUno);
            int b = Integer.parseInt(numeroDos);
            int resultado = a*b;
            this.lblResultado.setText(Integer.toString(resultado));
        }
        if(this.optDivision.isSelected()){
            float a = Float.parseFloat(numeroUno);
            float b = Float.parseFloat(numeroDos);
            float resultado = a/b;
            this.lblResultado.setText(Float.toString(resultado));
        }
        /*
        switch(_operacion){
            case "suma":
                System.out.println("suma");
            break;
            case "resta":
                System.out.println("resta");
            break;
            case "multiplicacion":
                System.out.println("multiplicacion");
            break;
            case "division":
                System.out.println("division");
            break;    
        }
                */
    }//GEN-LAST:event_btnCalcularActionPerformed
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCalcular;
    private javax.swing.JButton btnCerrar;
    private javax.swing.JButton btnDivision;
    private javax.swing.JButton btnMultiplicacion;
    private javax.swing.JButton btnResta;
    private javax.swing.JButton btnSuma;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JLabel lblResultado;
    private javax.swing.JRadioButton optDivision;
    private javax.swing.JRadioButton optMultiplicacion;
    private javax.swing.JRadioButton optResta;
    private javax.swing.JRadioButton optSuma;
    private javax.swing.JTextField txtNumeroDos;
    private javax.swing.JTextField txtNumeroUno;
    // End of variables declaration//GEN-END:variables
}
